Update from PrismTech repository of 4.1.090617

diff --git a/bin/checkconf b/bin/checkconf
--- a/bin/checkconf
+++ b/bin/checkconf
@@ -13,6 +13,11 @@ convert_windows_path ()
 {
     case `uname` in
         CYGWIN_NT*)
+            if [ ! -d "$1" ]
+            then
+            	  echo "Error: Path $1 does not exist"
+            	  return 1
+            fi
             #Make it a dos path to remove all spaces
             DOS_CONV_PATH=`cygpath -d "$1"`
             if [ $? != 0 ]
@@ -38,8 +43,7 @@ convert_windows_path ()
 
 csharp_check ()
 {
-    REQUIRED_VERSION="2.0.50727"
-    REQUIRED_VERSION=`echo $REQUIRED_VERSION | sed -e 's;\.;0;g'`
+    REQUIRED_VERSION="v2.0.50727"
     echo -n "C#: "
     pathcheck csc.exe
     if [ $? != 0 ]
@@ -53,13 +57,45 @@ csharp_check ()
         VERSIONS=`ls /cygdrive/$MAIN_DRIVE/Windows/Microsoft.NET/Framework | grep -E ^v`
         for i in $VERSIONS
         do
-            NET_VERSION=`echo $i | sed -e 's;\.;0;g' | tr -d 'v'`
-            if [ "$NET_VERSION" -ge "$REQUIRED_VERSION" ]
+            NET_VERSION=`echo $i | tr -d '/'`
+            echo "$REQUIRED_VERSION $NET_VERSION" | \
+            awk ' \
+            FS="" ;\
+            { \
+                vera1 = gensub( "^v([0-9]*).(.*)$", "\\1", 1 ) ; \
+                vera2 = gensub( "^v([0-9]*).([0-9]*)(.*)$", "\\2", 1 ) ;\
+                vera3 = gensub( "^v([0-9]*).([0-9]*).?([0-9]*)(.*)$", "\\3", 1 ) ;\
+                verb1 = gensub( ".* v([0-9]*).([0-9]*).?([0-9]*)$", "\\1", 1 ) ; \
+                verb2 = gensub( ".* v([0-9]*).([0-9]*).?([0-9]*)$", "\\2", 1 ) ;\
+                verb3 = gensub( ".* v([0-9]*).([0-9]*).?([0-9]*)$", "\\3", 1 ) ;\
+                if ( ( int(vera1) > int(verb1) ) \
+                  || ( ( int(vera1) == int(verb1) ) && ( int(vera2) >  int(verb2) ) ) \
+                  || ( ( int(vera1) == int(verb1) ) && ( int(vera2) == int(verb2) ) \
+                  && (int(vera3) > int(verb3) ) ) ) \
+                { \
+                    exit 0 ; \
+                } \
+                else \
+                { \
+                    exit 1 ; \
+                } \
+            }'
+            if [ "$?" = "1" ]
             then
+                if [ ! -f "/cygdrive/$MAIN_DRIVE/Windows/Microsoft.NET/Framework/$i/csc.exe" ]
+                then
+                    continue
+                fi
+
                 PATH=/cygdrive/$MAIN_DRIVE/Windows/Microsoft.NET/Framework/$i:$PATH
                 break
-            fi
+            fi            
         done
+        if [ ! -f "/cygdrive/$MAIN_DRIVE/Windows/Microsoft.NET/Framework/$i/csc.exe" ]
+        then
+            echo "Error - no valid Microsoft.NET Framwork compiler installed"
+            return 1
+        fi
     else
         CSC_EXE=`which csc`
         if [ "$CSC_EXE" = "/usr/bin/csc" -o  "$CSC_EXE" = "/bin/csc" ]
@@ -144,7 +180,8 @@ msvs_check ()
         COMPILER_VER="VS .NET 2008"
 
         LIB="$DOS_CONV_PATH\VC\LIB;"
-        FrameworkSDKDir="$UNIX_CONV_PATH/../Microsoft SDKs/Windows/v6.0A"
+        SDK_DIR="$UNIX_CONV_PATH/../Microsoft SDKs/Windows/v6.0A"
+        FrameworkSDKDir=`cygpath -d "$SDK_DIR"`
 		  PATH="$FrameworkSDKDir/bin:$PATH"
         export FrameworkSDKDir
         export LIB
@@ -451,8 +488,7 @@ tao_check ()
     fi
     
     export SPLICE_ORB
-
-    echo "OK - using TAO $TAO_VERSION as SPLICE_ORB"
+    echo "OK - SPLICE_ORB is TAO $TAO_VERSION"
     echo "  setting TAO_ROOT to $TAO_ROOT"
     return 0
 }
